-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 21, 2020 at 08:41 AM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `project1`
--

-- --------------------------------------------------------

--
-- Table structure for table `interprestation`
--

CREATE TABLE `interprestation` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `symbol` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `short` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `improvement` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `profession` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `partner` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `interprestation`
--

INSERT INTO `interprestation` (`id`, `symbol`, `short`, `description`, `improvement`, `profession`, `partner`, `created_at`, `updated_at`) VALUES
(1, 'ISTJ', 'Bertanggungjawab', 'Serius, tenang, stabil & damai.\r\nSenang pada fakta, logis, obyektif, praktis & realistis.\r\nTask oriented, tekun, teratur, menepati janji, dapat diandalkan & bertanggung jawab.\r\nPendengar yang baik, setia, hanya mau berbagi dengan orang dekat.\r\nMemegang aturan, standar & prosedur dengan teguh.', 'Belajarlah memahami perasaan & kebutuhan orang lain.\r\nKurangi keinginan untuk mengontrol orang lain atau memerintah mereka untuk menegakkan aturan.\r\nLihatlah lebih banyak sisi positif pada orang lain atau hal lainnya.\r\nTerbukalah terhadap perubahan.', 'Bidang Manajemen, Polisi, Intelijen, Hakim, Pengacara, Dokter, Akuntan (Staf Keuangan), Programmer atau yang berhubungan dengan IT, System Analys, Pemimpin Militer', 'Pasangan/Partner Alami: ESFP atau ESTP', '2020-05-20 10:35:48', '2020-05-20 10:35:48'),
(2, 'ISFJ', 'Setia', 'Penuh pertimbangan, hati-hati, teliti dan akurat.\r\nSerius, tenang, stabil namun sensitif.\r\nRamah, perhatian pada perasaan & kebutuhan orang lain, setia, kooperatif, pendengar yang baik.\r\nPunya kemampuan mengorganisasi, detail, teliti, sangat bertanggungjawab & bisa diandalkan.', 'Lihat lebih dalam, lebih antusias, & lebih semangat.\r\nBelajarlah mengatakan ”tidak”. Jangan menyenangkan semua orang atau Anda dianggap plin plan.\r\nJangan terjebak zona nyaman dan rutinitas. Cobalah hal baru. Ada banyak hal menyenangkan yang mungkin belum pernah Anda coba.', 'Architect, Interior Designer, Perawat, Administratif, Designer, Child Care, Konselor, Back Office Manager, Penjaga Toko / Perpustakaan, Dunia Perhotelan.', 'Pasangan/Partner Alami: ESFP atau ESTP', '2020-05-20 10:36:43', '2020-05-20 10:36:43'),
(3, 'ISTP', 'Pragmatis', 'Tenang, pendiam, cenderung kaku, dingin, hati-hati, penuh pertimbangan.\r\nLogis, rasional, kritis, obyektif, mampu mengesampingkan perasaan.\r\nMampu menghadapi perubahan mendadak dengan cepat dan tenang.\r\nPercaya diri, tegas dan mampu menghadapi perbedaan maupun kritik.\r\nMampu menganalisa, mengorganisir, & mendelegasikan.\r\nProblem solver yang baik terutama untuk masalah teknis & keadaan mendadak.', 'Observasilah kehidupan sosial, apa yang membuat orang marah, cinta, senang, termotivasi & terapkan pada hubungan Anda.\r\nBelajarlah untuk mengenali perasaan Anda dan mengekspresikannya.\r\nJadilah orang yang lebih terbuka, keluar dari zona nyaman, eksplorasi ide baru, dan berdiskusi dengan orang lain.\r\nJangan mencari-cari kesalahan orang hanya untuk menyelesaikan masalahnya.\r\nJangan menyimpan informasi yang harusnya dibagi dan belajarlah mempercayakan tanggungjawab pada orang lain.', 'Saran Profesi: Polisi, Ahli Forensik, Programmer, Ahli Komputer, System Analyst, Teknisi, Insinyur, Mekanik, Pilot, Atlit, Entrepreneur', 'Pasangan/Partner Alami: ESTJ atau ENTJ', '2020-05-20 10:37:20', '2020-05-20 10:37:20'),
(4, 'ISFP', 'Artistik', 'Berpikiran simpel & praktis, fleksibel, sensitif, ramah, tidak menonjolkan diri, rendah hati pada kemampuannya.\r\nMenghindari konflik, tidak memaksakan pendapat atau nilai-nilainya pada orang lain.\r\nBiasanya tidak mau memimpin tetapi menjadi pengikut dan pelaksana yang setia.\r\nSeringkali santai menyelesaikan sesuatu, karena sangat menikmati apa yang terjadi saat ini.\r\nMenunjukkan perhatian lebih banyak melalui tindakan dibandingkan kata-kata.', 'Jangan takut pada penolakan dan konflik. Anda tidak perlu menyenangkan semua orang.\r\nCobalah untuk mulai memikirkan dampak jangka panjang dari keputusan-keputusan kecil di hari ini.\r\nAsah dan kembangkan sisi kreatifitas dan seni dalam diri Anda sebagai modal bagus dalam diri Anda.\r\nCobalah untuk lebih terbuka dan mengekspresikan perasaan Anda.', 'Seniman, Designer, Pekerja Sosial, Konselor, Psikolog, Guru, Aktor, Bidang Hospitality', 'Pasangan/Partner Alami: ESFJ atau ENFJ', '2020-05-20 10:37:53', '2020-05-20 10:37:53'),
(5, 'INFJ', 'Reflektif', 'Perhatian, empati, sensitif & berkomitmen terhadap sebuah hubungan.\r\nSukses karena ketekunan, originalitas dan keinginan kuat untuk melakukan apa saja yang diperlukan termasuk memberikan yg terbaik dalam pekerjaan.\r\nIdealis, perfeksionis, memegang teguh prinsip.\r\nVisioner, penuh ide, kreatif, suka merenung dan inspiring.\r\nBiasanya diikuti dan dihormati karena kejelasan visi serta dedikasi pada hal-hal baik.', 'Seimbangkan cara pandang Anda. Jangan hanya melihat sisi negatif & resiko. Namun, lihatlah sisi positif dan peluangnya.\r\nBersabarlah, jangan mudah marah dan menyalahkan orang lain atau situasi.\r\nRileks dan jangan terus menerus berfikir atau menyelesaikan tanggungjawab.', 'Pengajar, Psikolog, Dokter, Konselor, Pekerja Sosial, Fotografer, Seniman, Designer, Child Care.', 'Pasangan/Partner Alami: ESFP atau ESTP', '2020-05-20 10:38:25', '2020-05-20 10:38:25'),
(6, 'INTJ', 'Independen', 'Visioner, punya perencanaan praktis, & biasanya memiliki ide-ide original serta dorongan kuat untuk mencapainya.\r\nMandiri dan percaya diri.\r\nPunya kemampuan analisa yang bagus serta menyederhanakan sesuatu yang rumit dan abstrak menjadi sesuatu yang praktis, mudah difahami & dipraktekkan.\r\nSkeptis, kritis, logis, menentukan (determinatif) dan kadang keras kepala.\r\nPunya keinginan untuk berkembang serta selalu ingin lebih maju dari orang lain.\r\nKritik & konflik tidak menjadi masalah berarti.', 'Belajarlah mengungkapkan emosi & perasaan Anda.\r\nCobalah untuk lebih terbuka pada dunia luar, banyak bergaul, banyak belajar, banyak membaca, mengunjungi banyak tempat, eksplorasi hal baru, & memperluas wawasan.\r\nHindari perdebatan tidak penting.\r\nBelajarlah untuk berempati, memberi perhatian dan lebih peka terhadap orang lain.', 'Peneliti, Ilmuwan, Insinyur, Teknisi, Pengajar, Profesor, Dokter, Research & Development, Business Analyst, System Analyst, Pengacara, Hakim, Programmers, Posisi Strategis dalam organisasi.', 'Pasangan/Partner Alami: ENFP atau ENTP', '2020-05-20 10:39:16', '2020-05-20 10:39:16'),
(7, 'INFP', 'Idealis', 'Sangat perhatian dan peka dengan perasaan orang lain.\r\nPenuh dengan antusiasme dan kesetiaan, tapi biasanya hanya untuk orang dekat.\r\nPeduli pada banyak hal. Cenderung mengambil terlalu banyak dan menyelesaikan sebagian.\r\nCenderung idealis dan perfeksionis.\r\nBerpikir win-win solution, mempercayai dan mengoptimalkan orang lain.', 'Belajarlah menghadapi kritik. Jika baik maka kritik itu bisa membangun Anda, namun jika tidak abaikan saja. Jangan ragu pula untuk bertanya dan minta saran.\r\nBelajarlah untuk bersikap tegas. Jangan selalu berperasaan dan menyenangkan orang dengan tindakan baik. Bertindak baik itu berbeda dengan bertindak benar.\r\nJangan terlalu menyalahkan diri dan bersikap terlalu keras pada diri sendiri. Kegagalan adalah hal biasa dan semua orang pernah mengalaminya.\r\nJangan terlalu baik pada orang lain tapi melupakan diri sendiri. Anda juga punya tanggungjawab untuk berbuat baik pada diri sendiri.', 'Penulis, Sastrawan, Konselor, Psikolog, Pengajar, Seniman, Rohaniawan, Bidang Hospitality', 'Pasangan/Partner Alami: ENFJ atau ESFJ', '2020-05-20 10:39:54', '2020-05-20 10:39:54'),
(8, 'INTP', 'Konseptual', 'Sangat menghargai intelektualitas dan pengetahuan. Menikmati hal-hal teoritis dan ilmiah. Senang memecahkan masalah dengan logika dan analisa.\r\nDiam dan menahan diri. Lebih suka bekerja sendiri.\r\nCenderung kritis, skeptis, mudah curiga dan pesimis.\r\nTidak suka memimpin dan bisa menjadi pengikut yang tidak banyak menuntut.\r\nCenderung memiliki minat yang jelas. Membutuhkan karir dimana minatnya bisa berkembang dan bermanfaat. Jika menemukan sesuatu yang menarik minatnya, ia akan sangat serius dan antusias menekuninya.', 'Belajarlah membangun hubungan dengan orang lain. Belajar berempati, mendengar aktif, memberi perhatian dan bertukar pendapat.\r\nRelaks. Jangan terlalu banyak berfikir. Nikmati hidup Anda tanpa harus bertanya mengapa dan bagaimana.\r\nCobalah menemukan satu ide, merencanakan dan mewujudkannya. Jangan terlalu sering berganti-ganti ide tetapi tidak satupun yang terwujud.', 'Ilmuwan, Fotografer, Programmer, Ahli komputer, System Analyst, Penulis Buku Teknis, Ahli Forensik, Jaksa, Pengacara, Teknisi', 'Pasangan/Partner Alami: ENTJ atau ESTJ', '2020-05-20 10:40:24', '2020-05-20 10:40:24'),
(9, 'ESTP', 'Spontan', 'Spontan, Aktif, Enerjik, Cekatan, Cepat, Sigap, Antusias, Fun dan penuh variasi.\r\nKomunikator, asertif, to the point, ceplas-ceplos, berkarisma, punya interpersonal skill yang baik.\r\nBaik dalam pemecahan masalah langsung di tempat. Mampu menghadapi masalah, konflik dan kritik. Tidak khawatir, menikmati apapun yang terjadi.\r\nCenderung untuk menyukai sesuatu yang mekanistis, kegiatan bersama dan olahraga.\r\nMudah beradaptasi, toleran, pada umumnya konservatif tentang nilai-nilai. Tidak suka penjelasan terlalu panjang. Paling baik dalam hal-hal nyata yang dapat dilakukan.', 'Belajarlah memahami perasaan dan pemikiran orang lain terutama saat bicara dengan mereka.\r\nBelajarlah untuk sabar, menikmati proses, tidak semua hal bisa dicapai dengan cepat.\r\nSesekali luangkan waktu untuk merenung dan merencanakan masa depan Anda.\r\nCobalah untuk mencatat pengamatan-pengamatan Anda termasuk detailnya.', 'Marketing, Sales, Polisi, Entrepreneur, Pialang Saham, Technical Support', 'Pasangan/Partner Alami: ISFJ atau ISTJ', '2020-05-20 10:41:55', '2020-05-20 10:41:55'),
(10, 'ESFP', 'Murah Hati', 'Outgoing, easygoing, mudah berteman, bersahabat, sangat sosial, ramah, hangat, & menyenangkan.\r\nOptimis, ceria, antusias, fun, menghibur, suka menjadi perhatian.\r\nPunya interpersonal skill yang baik, murah hati, mudah simpatik dan mengenali perasaan orang lain. Menghindari konflik dan menjaga keharmonisan suatu hubungan.\r\nMengetahui apa yang terjadi di sekelilingnya dan ikut serta dalam kegiatan tersebut.\r\nSangat baik dalam keadaan yang membutuhkan common sense, tindakan cepat dan ketrampilan praktis.', 'Jangan terburu-buru dalam mengambil keputusan. Belajarlah untuk fokus dan tidak mudah berubah-ubah terutama untuk hal yang penting.\r\nJangan menyenangkan semua orang. Begitu pula sebaliknya, tidak semua orang bisa menyenangkan Anda.\r\nBelajarlah menghadapi kritik dan konflik. Jangan lari.\r\nAnda punya kecenderungan meterialistis. Hati-hati, tidak semua hal bisa diukur dengan materi ataupun uang.', 'Entertainer, Seniman, Marketing, Konselor, Designer, Tour Guide, Bidang Anak-anak, Bidang Hospitality', 'Pasangan/Partner Alami: ISTJ atau ISFJ', '2020-05-20 10:42:31', '2020-05-20 10:42:31'),
(11, 'ENFP', 'Optimis', 'Ramah, hangat, enerjik, optimis, antusias, semangat tinggi, fun.\r\nImaginatif, penuh ide, kreatif, inovatif.\r\nMampu beradaptasi dengan beragam situasi dan perubahan.\r\nPandai berkomunikasi, senang bersosialisasi & membawa suasana positif.\r\nMudah membaca perasaan dan kebutuhan orang lain.', 'Belajarlah untuk fokus, disiplin, tegas dan konsisten\r\nBelajarlah untuk menghadapi konflik dan kritik.\r\nPikirkan kebutuhan diri sendiri. Jangan melupakannya karena terlalu peduli pada kebutuhan orang lain.\r\nJangan terlalu boros. Belajarlah untuk mengelola keuangan sedikit demi sedikit.', 'Konselor, Psikolog, Entertainer, Pengajar, Motivator, Presenter, Reporter, MC, Seniman, Hospitality', 'Pasangan/Partner Alami: INTJ atau INFJ', '2020-05-20 10:43:03', '2020-05-20 10:43:03'),
(12, 'ENTP', 'Inovatif – Kreatif', 'Gesit, kreatif, inovatif, cerdik, logis, baik dalam banyak hal.\r\nBanyak bicara dan punya kemampuan debat yang baik. Bisa berargumentasi untuk senang-senang saja tanpa merasa bersalah.\r\nFleksibel. Punya banyak cara untuk memecahkan masalah dan tantangan.\r\nKurang konsisten. Cenderung untuk melakukan hal baru yang menarik hati setelah melakukan sesuatu yang lain.\r\nPunya keinginan kuat untuk mengembangkan diri.', 'Cobalah untuk win-win solution. Jangan ingin menang sendiri.\r\nBelajarlah untuk disiplin dan konsisten.\r\nHindari perdebatan tidak penting.\r\nBelajarlah untuk sedikit waspada. Seimbangkan cara pandang Anda agar tidak terlalu optimis dan mengambil resiko yang tidak realistis.\r\nBelajarlah untuk memberi perhatian pada perasaan orang lain.', 'Pengacara, Psikolog, Konsultan, Ilmuwan, Aktor,Marketing, Programmer, Fotografer', 'Pasangan/Partner Alami: INFJ atau INTJ', '2020-05-20 10:43:34', '2020-05-20 10:43:34'),
(13, 'ESTJ', 'Konservatif – Disiplin', 'Praktis, realistis, berpegang pada fakta, dengan dorongan alamiah untuk bisnis dan mekanistis.\r\nSangat sistematis, procedural dan terencana.\r\nDisiplin, on time dan pekerja keras.\r\nKonservatif dan cenderung kaku.\r\nTidak tertarik pada subject yang tidak berguna baginya, tapi dapat menyesuaikan diri jika diperlukan.\r\nSenang mengorganisir sesuatu. Bisa menjadi administrator yang baik jika mereka ingat untuk memperhatikan perasaan dan perspektif orang lain.', 'Kurangi keinginan untuk mengontrol dan memaksa orang lain.\r\nBelajarlah untuk mengontrol emosi dan amarah Anda.\r\nCobalah untuk introspeksi diri dan meluangkan waktu sejenak untuk merenung.\r\nBelajarlah untuk lebih sabar dan low profile\r\nBelajarlah untuk memahami orang lain.', 'Militer, Manajer, Polisi, Hakim, Pengacara, Guru, Sales, Auditor, Akuntan, System Analyst', 'Pasangan/Partner Alami: ISTP atau INTP', '2020-05-20 10:44:51', '2020-05-20 10:44:51'),
(14, 'ESFJ', 'Harmonis', 'Hangat, banyak bicara, populer, dilahirkan untuk bekerjasama, suportif dan anggota kelompok yang aktif.\r\nMembutuhkan keseimbangan dan baik dalam menciptakan harmoni.\r\nSelalu melakukan sesuatu yang manis bagi orang lain. Kerja dengan baik dalam situasi yang mendukung dan memujinya.\r\nSantai, easy going, sederhana, tidak berfikir panjang.\r\nTeliti dan rajin merawat apa yang ia miliki.', 'Jangan mengorbankan diri hanya untuk menyenangkan orang lain.\r\nJangan mengukur harga diri Anda dari perlakuan, penghargaan dan pujian orang lain.\r\nMintalah pertimbangan orang lain dalam mengambil keputusan. Belajarlah untuk lebih tegas.\r\nTerima tanggungjawab hidup dan belajarlah untuk lebih dewasa. Jangan mengasihani diri sendiri.\r\nHadapi kritik dan konflik, jangan lari.', 'Perencana Keuangan, Perawat, Guru, Bidang anak-anak, Konselor, Administratif, Hospitality', 'Pasangan/Partner Alami: ISFP atau INFP', '2020-05-20 10:45:23', '2020-05-20 10:45:23'),
(15, 'ENFJ', 'Meyakinkan', 'Kreatif, imajinatif, peka, sensitive, loyal.\r\nPada umumnya peduli pada apa kata orang atau apa yang orang lain inginkan dan cenderung melakukan sesuatu dengan memperhatikan perasaan orang lain.\r\nPandai bergaul, meyakinkan, ramah, fun, populer, simpatik. Responsif pada kritik dan pujian.\r\nMenyukai variasi dan tantangan baru.\r\nButuh apresiasi dan penerimaan.', 'Jangan mengorbankan diri hanya untuk menyenangkan orang lain.\r\nJangan mengukur harga diri Anda dari perlakuan orang lain. Jangan mudah kecewa jika mereka tidak seperti yang Anda inginkan.\r\nBelajarlah untuk tegas dan mengambil keputusan. Menghadapi kritik dan konflik.\r\nJangan terlalu bersikap keras terhadap diri sendiri.', 'Konsultan, Psikolog, Konselor, Pengajar, Marketing, HRD, Event Coordinator, Entertainer, Penulis, Motivator.', 'Pasangan/Partner Alami: INFP atau ISFP', '2020-05-20 10:45:58', '2020-05-20 10:45:58'),
(16, 'ENTJ', 'Pemimpin Alami', 'Tegas, asertif, to the point, jujur terus terang, obyektif, kritis, & punya standard tinggi.\r\nDominan, kuat kemauannya, perfeksionis dan kompetitif.\r\nTangguh, disiplin, dan sangat menghargai komitmen.\r\nCenderung menutupi perasaan dan menyembunyikan kelemahan.\r\nBerkarisma, komunikasi baik, mampu menggerakkan orang.\r\nBerbakat pemimpin.\r\nSaran Pengembangan:', 'Belajarlah untuk relaks. Tidak perlu perfeksionis dan selalu kompetitif dengan semua orang.\r\nUngkapkan perasaan Anda. Menyatakan perasaan bukanlah kelemahan.\r\nBelajarlah mengelola emosi Anda. Jangan mudah marah.\r\nBelajarlah untuk menghargai dan mengapresiasi orang lain.\r\nJangan terlalu arogan dan menganggap remeh orang lain. Lihat sisi positifnya. Jangan hanya melihat benar dan salah saja.', 'Entrepreneur, Pengacara, Hakim, Konsultan, Pemimpin Organisasi, Business analyst, Bidang Finansial', 'Pasangan/Partner Alami: INTP atau ISTP', '2020-05-20 10:46:33', '2020-05-20 10:46:33');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `interprestation`
--
ALTER TABLE `interprestation`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `interprestation`
--
ALTER TABLE `interprestation`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
